// <auto-generated />
namespace API_Notebook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Notebook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notebook));
        
        string IMigrationMetadata.Id
        {
            get { return "202008120459327_Notebook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
